sudo: false # Use docker containers rather than VMs -> faster
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -q -r requirements.txt -r doc/requirements_doc.txt
  - pip install .

script:
  - make test
  - make doc

