sudo: false # Use docker containers rather than VMs -> faster

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -q -r requirements.txt -r doc/requirements_doc.txt
  - pip install .

script:
  - make test
  - make doc

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b238f1b4f26967edf138 # Gitter channel
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
